language: python
python:
  - "3.5"

install:
  - pip install numpy
  - pip install coveralls
  - pip install cython
  - pip install pytest

script:
  - python -m unittest discover tests/
  #- py.test --pyargs /home/travis/build/KevinFasusi/supplychainpy/tests/
  - coverage run --source=/home/travis/build/KevinFasusi/supplychainpy/ -m unittest discover tests/
  #- coverage run --source=/home/travis/build/KevinFasusi/supplychainpy/ -m py.test --pyargs /home/travis/build/KevinFasusi/supplychainpy/tests/



after_success:
  - coveralls

notifications:
  email:
    - kevin@supplybi.com
