language: python
python:
  - "3.5"

install:
  - pip install numpy
  - pip install coveralls

script:
  - python -m unittest discover tests/
  - coverage run --omit=/home/travis/virtualenv/python3.5.0/ -m unittest discover tests/


after_success:
  - coveralls

notifications:
  email:
    - kevin@supplybi.com
